eps: 0.001
eval_mode: False
#eval_mode: True

# optimizer
lr: 0.0001
# train
data_dir: "/home/ubuntu/diffmot_root/sportsmot/trackers_gt/train" # '/mnt/8T/home/estar/data/DanceTrack/trackers_gt_GSI'
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 1200
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0]

# Testing
eval_at: 1200
embedding_dataset: "sportsmot"
det_dir: "/home/ubuntu/diffmot_root/sportsmot/detections/val"
info_dir: '/home/ubuntu/diffmot_root/sportsmot/val' # '/mnt/8T/home/estar/data/DanceTrack/val'
reid_dir: "/home/ubuntu/reid_embeddings/sportsmot/embeddings" #"/home/estar/lwy/DiffMOT/cache/embeddings/"
save_dir: "/home/ubuntu/diffmot_root/results" #"/mnt/8T/home/estar/data/DanceTrack/results/val/yolox_m_lt_ddm_1000eps_deeper_800_1rev"
eval_expname: lt_ddm_1000_deeper
high_thres: 0.6
low_thres: 0.4
w_assoc_emb: 2.0
aw_param: 1.2
preprocess_workers: 4

# Data Parameters:
device: cuda
eval_device: None
